// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjANe_mwiLEy1Y2y3_ccgYrE_vu5CNL80',
    appId: '1:80400507045:web:d3598cb8714bcee98f2d4c',
    messagingSenderId: '80400507045',
    projectId: 'sinifcepte',
    authDomain: 'sinifcepte.firebaseapp.com',
    storageBucket: 'sinifcepte.firebasestorage.app',
    measurementId: 'G-66Z7D8SYGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDba2S14xl196wAJJQNaE4DQAGuO6AYoAc',
    appId: '1:80400507045:android:5d281e20b9df396d8f2d4c',
    messagingSenderId: '80400507045',
    projectId: 'sinifcepte',
    storageBucket: 'sinifcepte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOh7ML5rUZB3coqS6aSU-Zn42RLR55L_0',
    appId: '1:80400507045:ios:db4e7b1acf43c4ee8f2d4c',
    messagingSenderId: '80400507045',
    projectId: 'sinifcepte',
    storageBucket: 'sinifcepte.firebasestorage.app',
    iosBundleId: 'com.sinifcepte.sinifcepte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjANe_mwiLEy1Y2y3_ccgYrE_vu5CNL80',
    appId: '1:80400507045:web:d0db6a17f5d158138f2d4c',
    messagingSenderId: '80400507045',
    projectId: 'sinifcepte',
    authDomain: 'sinifcepte.firebaseapp.com',
    storageBucket: 'sinifcepte.firebasestorage.app',
    measurementId: 'G-6LSD909SB1',
  );
}
